import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {seed,createRequest,act,priority,stats,filterRecords,toCSV,csvCell,advanceClock,validState,CLOCK} from '../dist/assets/model.mjs';
const results=[];
function test(id,name,fn,requirements){try{fn();results.push({id,name,requirements,result:'Pass',method:'Automated domain check',executedAt:new Date().toISOString()})}catch(e){results.push({id,name,requirements,result:'Fail',method:'Automated domain check',detail:e.message});process.exitCode=1}}
const payload={title:'Fictional printer fault',description:'Synthetic printer is unavailable to the team.',unit:'Riverbend',category:'Device',impact:'High',urgency:'Standard'};
const fresh=()=>({schema:1,now:CLOCK,records:[]});
function progressed(){const s=fresh(),r=createRequest(s,payload,'Requester');act(s,r.id,'assign','Coordinator',{owner:'Alex T.'});act(s,r.id,'start','Technician');return [s,r]}
test('T01','Valid fault creates a Submitted request and initial event',()=>{const s=fresh(),r=createRequest(s,payload,'Requester');assert.equal(r.id,'RF-1001');assert.equal(r.status,'Submitted');assert.equal(r.events.length,1);assert.equal(r.priority,'P2')},'R01');
test('T02','Invalid and whitespace input rejected without saving',()=>{const s=fresh();for(const input of [{...payload,title:' '},{...payload,description:'short'},{...payload,unit:'Real unit'},{...payload,title:'x'.repeat(121)},{...payload,urgency:'Invalid'}])assert.throws(()=>createRequest(s,input,'Requester'));assert.equal(s.records.length,0)},'R01');
test('T03','Unique references and assisted intake',()=>{const s=fresh();createRequest(s,payload,'Requester');const r=createRequest(s,payload,'Coordinator');assert.equal(r.id,'RF-1002');assert.equal(r.events[0].note,'Assisted intake');assert.throws(()=>createRequest(s,payload,'Technician'))},'R01, R10');
test('T04','Coordinator assignment records owner and event',()=>{const s=fresh(),r=createRequest(s,payload,'Requester');act(s,r.id,'assign','Coordinator',{owner:'Alex T.'});assert.equal(r.owner,'Alex T.');assert.equal(r.status,'Assigned');assert.equal(r.events.length,2)},'R02');
test('T05','Empty owner and wrong-role assignment fail atomically',()=>{const s=fresh(),r=createRequest(s,payload,'Requester'),before=JSON.stringify(s);assert.throws(()=>act(s,r.id,'assign','Coordinator',{owner:''}));assert.throws(()=>act(s,r.id,'assign','Requester',{owner:'Alex T.'}));assert.equal(JSON.stringify(s),before)},'R02');
test('T06','Assigned fault can start only with Technician role',()=>{const [s,r]=progressed();assert.equal(r.status,'In progress');assert.equal(r.events.length,3)},'R03');
test('T07','Skipped or unknown transitions leave data unchanged',()=>{const s=fresh(),r=createRequest(s,payload,'Requester'),before=JSON.stringify(s);for(const action of ['start','resolve','confirm','delete'])assert.throws(()=>act(s,r.id,action,'Technician',{note:'A sufficiently detailed note.'}));assert.equal(JSON.stringify(s),before)},'R03');
test('T08','All four priority combinations and target intervals',()=>{for(const [i,u,p,h] of [['High','High','P1',4],['High','Standard','P2',24],['Standard','High','P2',24],['Standard','Standard','P3',72]]){assert.equal(priority(i,u),p);const s=fresh(),r=createRequest(s,{...payload,impact:i,urgency:u},'Requester');assert.equal(Date.parse(r.dueAt)-Date.parse(CLOCK),h*3600000)}},'R04');
test('T09','Resolution requires adequate evidence and proper role',()=>{const [s,r]=progressed(),before=JSON.stringify(s);assert.throws(()=>act(s,r.id,'resolve','Technician',{note:'short'}));assert.throws(()=>act(s,r.id,'resolve','Coordinator',{note:'Detailed resolution evidence.'}));assert.equal(JSON.stringify(s),before);act(s,r.id,'resolve','Technician',{note:'Test printer restored and test page verified.'});assert.equal(r.status,'Awaiting confirmation');assert.equal(r.closedAt,null)},'R05');
test('T10','Requester confirmation closes once and stamps closure',()=>{const [s,r]=progressed();act(s,r.id,'resolve','Technician',{note:'Test printer restored and test page verified.'});assert.throws(()=>act(s,r.id,'confirm','Technician'));act(s,r.id,'confirm','Requester');assert.equal(r.status,'Closed');assert.equal(r.closedAt,CLOCK);assert.throws(()=>act(s,r.id,'confirm','Requester'))},'R06');
test('T11','Rejection requires reason, preserves history and returns to work',()=>{const [s,r]=progressed();act(s,r.id,'resolve','Technician',{note:'Test printer restored and test page verified.'});const count=r.events.length;assert.throws(()=>act(s,r.id,'reject','Requester',{note:'no'}));act(s,r.id,'reject','Requester',{note:'Test page still fails to print from the shared workstation.'});assert.equal(r.status,'In progress');assert.equal(r.events.length,count+1);assert.equal(r.closedAt,null);assert.ok(r.resolution.length>10);act(s,r.id,'resolve','Technician',{note:'Second configuration tested with a successful print.'});act(s,r.id,'confirm','Requester');assert.equal(r.status,'Closed')},'R06');
test('T12','Successful events retain roles, states and timestamps',()=>{const [s,r]=progressed();const history=JSON.stringify(r.events);assert.throws(()=>act(s,r.id,'confirm','Requester'));assert.equal(JSON.stringify(r.events),history);for(const e of r.events){assert.ok(e.role);assert.ok(e.status);assert.ok(Number.isFinite(Date.parse(e.at)))}},'R07');
test('T13','CSV quotes special characters and neutralises formula cells',()=>{assert.equal(csvCell('=SUM(A1:A2)'),`"'=SUM(A1:A2)"`);assert.equal(csvCell('  +1'),`"'  +1"`);assert.equal(csvCell('hello,"world"\nline'),`"hello,""world""\nline"`);const s=seed(),f=filterRecords(s,'Northbank');const csv=toCSV(f);assert.equal(f.length,2);assert.ok(csv.includes('RF-1002'));assert.ok(!csv.includes('RF-1001'))},'R08');
test('T14','Snapshot queue counts and clock-driven overdue changes',()=>{const s=seed();assert.deepEqual(stats(s),{open:6,overdue:2,awaiting:1,closed:2});advanceClock(s,24);assert.equal(stats(s).overdue,4);assert.equal(stats(s).closed,2);assert.throws(()=>advanceClock(s,-2));assert.ok(validState(s));assert.equal(validState({schema:1,records:[]}),false)},'R09');
test('T15','Search and status filters combine, with empty result',()=>{const s=seed();assert.equal(filterRecords(s,'riverbend','Submitted').length,2);assert.equal(filterRecords(s,'RF-1002').length,1);assert.equal(filterRecords(s,'Alex T.').length,2);assert.equal(filterRecords(s,'no matching request').length,0)},'R09');
const context={window:{}};vm.runInNewContext(fs.readFileSync(new URL('../dist/assets/evidence-data.js',import.meta.url),'utf8'),context);fs.writeFileSync(new URL('../evidence/project-data.json',import.meta.url),JSON.stringify(context.window.RELAY_EVIDENCE,null,2));
fs.writeFileSync(new URL('../evidence/test-results.json',import.meta.url),JSON.stringify({executedOn:'2026-10-09',scope:'Self-executed prototype domain tests; not business UAT or production assurance',results},null,2));
console.log(JSON.stringify({passed:results.filter(x=>x.result==='Pass').length,total:results.length,results},null,2));
